[config]
schemaVersion = "0.2.1"

[package]
namespace = "Binbin"
name = "Riffy_The_Riftwalker"
versionNumber = "0.2.1"
description = "New Hero Mod for Riffy, the Riftwalker. A new hero that specializes in x, y, and z"
websiteUrl = "https://github.com/binbinmods/Riffy"
containsNsfwContent = false

[package.dependencies]
meds-Obeliskial_Essentials = "1.5.1"
meds-Obeliskial_Content = "1.7.2"

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "./Riffy"
target = ""

[publish]
repository = "https://thunderstore.io"
communities = [ "across-the-obelisk", ]
[publish.categories]
across-the-obelisk = [ "mods", ]
